Repository temporalio/temporal, pull requests merged in 2022-10, with the labels that each got.

#3449 Fix reset workflow in replication reapply
  service/history/nDCTransactionMgr.go
  service/history/nDCTransactionMgr_test.go
Labels: release/1.18.1

#3447 Update replication use branch token
  api/persistence/v1/executions.pb.go
  common/persistence/serialization/task_serializer.go
  proto/internal/temporal/server/api/persistence/v1/executions.proto
  service/history/replication/ack_manager.go
  service/history/replication/ack_manager_test.go
  service/history/tasks/history_replication_task.go
  service/history/timerQueueTaskExecutorBase.go
  service/history/workflow/context.go
  service/history/workflow/task_generator.go
Labels: release/1.18.1

#3463 Use separate metric for resource exhausted error in task processing
  service/history/queues/executable.go
  service/history/queues/metrics.go
Labels: release/1.18.1

#3464 Compare task type enum
  common/dynamicconfig/client.go
  common/dynamicconfig/collection.go
  common/dynamicconfig/config/testConfig.yaml
  common/dynamicconfig/file_based_client.go
  common/dynamicconfig/file_based_client_test.go
Labels: release/1.18.1

#3466 Fix exclude tags with withTags method
  common/metrics/tally_metrics_handler.go
  common/metrics/tally_metrics_handler_test.go
Labels: release/1.18.1

#3470 Properly handle min task ID > max task ID case when shard is re-balancing
  service/history/replication/ack_manager.go
Labels: release/1.18.2

#3474 Fix scheduled queue max read level update for single processor
  service/history/queues/queue_base.go
  service/history/replication/ack_manager.go
  service/history/replication/ack_manager_test.go
  service/history/replication/task_processor_manager.go
  service/history/replication/task_processor_manager_test.go
  service/history/shard/context.go
  service/history/shard/context_impl.go
  service/history/shard/context_mock.go
  service/history/shard/context_test.go
  service/history/timerQueueAckMgr.go
  service/history/timerQueueAckMgr_test.go
  service/history/timerQueueActiveProcessor.go
  service/history/timerQueueStandbyProcessor.go
  service/history/transferQueueActiveProcessor.go
  service/history/transferQueueStandbyProcessor.go
  service/history/visibilityQueueProcessor.go
Labels: release/1.18.2

#3462 Turns on the history scavenger for SQL backends
  service/worker/scanner/scanner.go
  service/worker/scanner/scanner_test.go
  service/worker/service.go
Labels: release/1.18.2

#3479 Fix sanitize mutable state after replication
  common/constants.go
  host/xdc/integration_failover_test.go
  service/history/ndc/history_replicator.go
  service/history/shard/context_impl.go
  service/history/workflow/mutable_state_impl.go
  service/history/workflow/mutable_state_impl_test.go
Labels: release/1.18.2

#3457 Add execution scavenger for retention
  common/dynamicconfig/constants.go
  service/worker/scanner/executions/mutable_state_validator.go
  service/worker/scanner/executions/scavenger.go
  service/worker/scanner/executions/task.go
  service/worker/scanner/scanner.go
  service/worker/scanner/scanner_test.go
  service/worker/scanner/workflow.go
  service/worker/service.go
Labels: release/1.18.2

#3487 Update replication timestamp with no task
  service/history/replication/task_processor.go
Labels: release/1.18.2

#3509 Rewrite mysql PaginateBranchesFromHistoryTree query
  common/persistence/sql/sqlplugin/mysql/events.go
Labels: release/1.18.2

#3508 Warning log on new event during set workflow
  common/metrics/defs.go
  service/history/workflow/context.go
Labels: release/1.18.2

#3526 Change execution scavenger to call admin delete
  common/dynamicconfig/constants.go
  service/worker/scanner/executions/scavenger.go
  service/worker/scanner/executions/task.go
  service/worker/scanner/scanner.go
  service/worker/scanner/scanner_test.go
  service/worker/scanner/workflow.go
  service/worker/service.go
Labels: release/1.18.4

#3531 Fix replication task nil case
  service/history/replication/ack_manager.go
Labels: release/1.18.4

#3530 Port util.CloneMapNonNil to release branch
  common/payload/payload.go
  common/util/util.go
  service/worker/addsearchattributes/workflow.go
  service/worker/scheduler/workflow.go
Labels: release/1.18.4

#3541 Add retention validation in history scavenger
  common/dynamicconfig/constants.go
  service/worker/scanner/history/scavenger.go
  service/worker/scanner/history/scavenger_test.go
  service/worker/scanner/scanner.go
  service/worker/scanner/workflow.go
  service/worker/service.go
Labels: release/1.18.4

#3546 Take rpc address from config for local cluster
  temporal/fx.go
Labels: release/1.18.4
