Repository temporalio/temporal, pull requests merged in 2022-08, with the labels that each got.

#3173 Fix tally timer metric
  common/metrics/config.go
  common/metrics/tally_metrics_handler.go
  common/metrics/tally_metrics_handler_test.go
Labels: release/1.17.2

#3194 Use detached context for shard context operations
  service/history/shard/context_impl.go
Labels: release/1.17.3

#3195 Fix queue processor throttling logic
  service/history/queueProcessor.go
Labels: release/1.17.3

#3201 Use a prefix for scheduler workflow ids
  service/frontend/workflowHandler.go
  service/worker/scheduler/workflow.go
Labels: release/1.17.3

#3215 Fix shard close error type
  service/history/queueProcessor.go
  service/history/shard/context_impl.go
  service/history/shard/controller_impl.go
  service/history/timerQueueProcessor.go
  service/history/timerQueueProcessorBase.go
  service/history/transferQueueProcessor.go
  service/history/visibilityQueueProcessor.go
Labels: release/1.17.3

#3216 Fix inline history archival
  service/history/fx.go
  service/history/workflow/delete_manager.go
  service/history/workflow/delete_manager_test.go
  service/worker/archiver/client.go
  service/worker/archiver/client_test.go
Labels: release/1.17.3

#3218 Improve task processing retry behavior
  common/util.go
  service/history/queues/executable.go
Labels: release/1.17.3

#3227 Fix archival activities error handling
  service/worker/archiver/activities.go
  service/worker/archiver/activities_test.go
  service/worker/archiver/handler.go
Labels: release/1.17.3

#3232 Fix failover queue shutdown
  service/history/historyEngineInterfaces.go
  service/history/historyEngineInterfaces_mock.go
  service/history/queueProcessorBase.go
  service/history/timerQueueProcessorBase.go
Labels: release/1.17.3

#3251 Evenly distributed frontend global rps limit
  common/dynamicconfig/constants.go
  service/frontend/fx.go
  service/frontend/service.go
Labels: release/1.18.0

#3263 Add `--allow-no-auth` flag to allow noopAuthorizer
  cmd/server/main.go
  common/authorization/authorizer.go
  common/config/loader.go
Labels: release/1.18.0

#3285 Remove frontend handler retries
  common/util.go
  service/frontend/fx.go
Labels: release/1.17.5
