Repository temporalio/temporal, pull requests merged in 2023-07, with the labels that each got.

#4598 Fix MySQL 8 upgrade script to schema v1.3
  schema/mysql/v8/visibility/versioned/v1.3/add_build_ids_search_attribute.sql
Labels: release/1.21.2

#4571 properly fix migration in mem ack aggregation
  service/history/shard/context_impl.go
  service/history/shard/context_test.go
Labels: release/1.21.2

#4604 Disable user data when fetch fails
  service/matching/config.go
  service/matching/db.go
  service/matching/matching_engine.go
  service/matching/task_queue_manager.go
  service/matching/task_queue_manager_test.go
  service/matching/task_reader.go
  tests/versioning_test.go
Labels: release/1.21.2

#4610 Send default tasks to unversioned queue when user data disabled
  service/frontend/workflow_handler.go
  service/matching/matching_engine.go
  service/matching/matching_engine_test.go
  service/matching/task_queue_manager_test.go
  tests/versioning_test.go
Labels: release/1.21.2

#4617 Handle replicate workflow state with exist workflow data
  service/history/ndc/history_replicator.go
  service/history/ndc/history_replicator_test.go
  service/history/replication/executable_workflow_state_task.go
  service/history/replication/executable_workflow_state_task_test.go
  service/history/replication/task_executor.go
  tests/ndc/ndc_integration_test.go
Labels: release/1.21.3

#4624 Add BuildIds predefined search attribute
  common/searchattribute/defs.go
Labels: release/1.20.4

#4625 Fix metrics tagging in stream replication task processing
  service/history/replication/executable_task.go
Labels: release/1.21.3

#4626 Drop standby tasks in standby taks executor
  common/namespace/registry.go
  service/history/archival_queue_task_executor_test.go
  service/history/queues/executable.go
  service/history/queues/executable_test.go
  service/history/timer_queue_standby_task_executor.go
  service/history/transfer_queue_standby_task_executor.go
Labels: release/1.21.3

#4632 Do not generate visibility task for unchanged BuildIds
  service/history/workflow/mutable_state_impl.go
Labels: release/1.21.2

#4637 Exclude history APIs from persistence health signals
  common/persistence/persistence_metric_clients.go
Labels: release/1.21.3

#4645 Allow configurating history cache non-user context lock timeout
  common/dynamicconfig/constants.go
  service/history/configs/config.go
  service/history/workflow/cache/cache.go
Labels: release/1.21.3

#4647 Better handle admin handler stream replication API lifecycle
  service/frontend/admin_handler.go
  service/frontend/admin_handler_test.go
  service/history/replication/stream_receiver_monitor.go
Labels: release/1.21.3

#4648 Log when health rate limiter value changes
  common/log/tag/zap_tag.go
  common/persistence/client/health_request_rate_limiter.go
Labels: release/1.21.3

#4614 Add support for ES Scroll for Scan API
  common/persistence/visibility/store/elasticsearch/client/client.go
  common/persistence/visibility/store/elasticsearch/client/client_mock.go
  common/persistence/visibility/store/elasticsearch/client/client_v7.go
  common/persistence/visibility/store/elasticsearch/visibility_store.go
  common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
Labels: release/1.21.3

#4655 Custom search attributes validation per store
  common/persistence/visibility/manager/visibility_manager.go
  common/persistence/visibility/manager/visibility_manager_mock.go
  common/persistence/visibility/store/elasticsearch/visibility_store.go
  common/persistence/visibility/store/errors.go
  common/persistence/visibility/store/sql/visibility_store.go
  common/persistence/visibility/store/standard/cassandra/visibility_store.go
  common/persistence/visibility/store/standard/sql/visibility_store.go
  common/persistence/visibility/store/standard/visibility_store.go
  common/persistence/visibility/store/visibility_store.go
  common/persistence/visibility/store/visibility_store_mock.go
  common/persistence/visibility/visibility_manager_dual.go
  common/persistence/visibility/visibility_manager_impl.go
  common/persistence/visibility/visibility_manager_rate_limited.go
  common/persistence/visibility/visiblity_manager_metrics.go
  common/searchattribute/validator.go
  common/searchattribute/validator_test.go
  service/frontend/workflow_handler.go
  service/history/command_checker_test.go
  service/history/history_engine.go
  service/history/history_engine2_test.go
  service/history/workflow_task_handler_callbacks_test.go
Labels: release/1.21.3

#4663 Validate workflow task start time when complete
  api/token/v1/message.pb.go
  common/tasktoken/token.go
  proto/internal/temporal/server/api/token/v1/message.proto
  service/frontend/workflow_handler.go
  service/history/api/startworkflow/api.go
  service/history/workflow_task_handler_callbacks.go
  service/matching/matching_engine.go
  tests/update_workflow_test.go
Labels: release/1.21.3
