Repository temporalio/temporal, pull requests merged in 2023-10, with the labels that each got.

#4920 Make rate multi min and max dynamic
  common/dynamicconfig/shared_constants.go
  common/persistence/client/health_request_rate_limiter.go
Labels: release/1.22.1

#4932 Improve XDC logging
  service/worker/replicator/namespace_replication_message_processor.go
Labels: release/1.22.1

#4933 Use RateBurst in RateLimitInterceptorProvider
  service/frontend/fx.go
Labels: release/1.22.1

#4911 Don't track overlapping scheduled workflows
  service/worker/scheduler/testdata/replay_v1.22.0.json.gz
  service/worker/scheduler/testdata/replay_v1.23-pre.json.gz
  service/worker/scheduler/workflow.go
  service/worker/scheduler/workflow_test.go
Labels: release/1.22.1

#4970 Lock get current execution for API requests
  common/dynamicconfig/constants.go
  service/history/api/activity_util.go
  service/history/api/consistency_checker.go
  service/history/api/consistency_checker_test.go
  service/history/api/get_workflow_util.go
  service/history/api/queryworkflow/api.go
  service/history/api/resetworkflow/api.go
  service/history/api/startworkflow/api.go
  service/history/configs/config.go
  service/history/tests/vars.go
  tests/onebox.go
Labels: release/1.22.1

#5030 Disable eager activities for incompatible versioned activities
  service/history/workflow_task_handler.go
  tests/versioning_test.go
Labels: release/1.22.2

#4990 Use ContinueAsNewSuggested in scheduler workflow
  service/worker/scheduler/workflow.go
  service/worker/scheduler/workflow_test.go
Labels: release/1.22.2

#5039 Bugfix: ImportWorkflow should always clear mutable state cache
  service/history/ndc/history_importer.go
  tests/ndc/ndc_test.go
Labels: release/1.23.0

#5043 Adjust action metrics
  common/rpc/interceptor/telemetry.go
Labels: release/1.22.2

#5036 Validate search attributes values in queries to ES
  common/persistence/visibility/factory.go
  common/persistence/visibility/store/elasticsearch/query_interceptors.go
  common/persistence/visibility/store/elasticsearch/query_interceptors_test.go
  common/persistence/visibility/store/elasticsearch/visibility_store.go
  common/persistence/visibility/store/elasticsearch/visibility_store_read_test.go
  common/persistence/visibility/store/query/converter.go
  common/persistence/visibility/store/standard/converter.go
  common/persistence/visibility/store/standard/converter_test.go
  common/persistence/visibility/store/standard/query_interceptors.go
  common/persistence/visibility/store/standard/visibility_store.go
Labels: release/1.22.2

#5034 Add force-continue-as-new signal to schedule workflow
  service/worker/scheduler/workflow.go
  service/worker/scheduler/workflow_test.go
Labels: release/1.22.2
