Repository temporalio/temporal, pull requests merged in 2025-06, with the labels that each got.

#7799 Add rate limiter on low priority replication tasks
  service/history/fx.go
  service/history/handler.go
  service/history/replication/batchable_task.go
  service/history/replication/batchable_task_mock.go
  service/history/replication/executable_task_tracker.go
  service/history/replication/executable_task_tracker_mock.go
  service/history/replication/fx.go
  service/history/replication/quotas.go
  service/history/replication/stream_sender.go
  service/history/replication/stream_sender_test.go
Labels: teams/cgs

#7886 Fix error message for catchup input validation
  service/worker/migration/catchup_workflow.go
Labels: teams/cgs

#7895 Add config flag for replication rate limiter
  common/dynamicconfig/constants.go
  common/metrics/metric_defs.go
  service/history/configs/config.go
  service/history/replication/fx.go
  service/history/replication/stream_sender.go
Labels: teams/cgs

#7911 Add workflowpb.PostResetOperation to ResetParams in batch operations
  service/frontend/workflow_handler.go
  service/frontend/workflow_handler_test.go
  service/worker/batcher/activities.go
  service/worker/batcher/workflow.go
Labels: release/1.28.0

#7915 Reset+version_move: fix decoding bug and add functional test
  service/frontend/workflow_handler.go
  service/frontend/workflow_handler_test.go
  tests/workflow_reset_test.go
Labels: release/1.28.0

#7745 Add new rate limiter priority to support high/low replication tier
  service/history/replication/eager_namespace_refresher.go
  service/history/replication/eager_namespace_refresher_mock.go
  service/history/replication/eager_namespace_refresher_test.go
  service/history/replication/executable_activity_state_task.go
  service/history/replication/executable_activity_state_task_test.go
  service/history/replication/executable_backfill_history_events_task.go
  service/history/replication/executable_backfill_history_events_task_test.go
  service/history/replication/executable_history_task.go
  service/history/replication/executable_history_task_test.go
  service/history/replication/executable_noop_task.go
  service/history/replication/executable_sync_hsm_task.go
  service/history/replication/executable_sync_hsm_task_test.go
  service/history/replication/executable_sync_versioned_transition_task.go
  service/history/replication/executable_task.go
  service/history/replication/executable_task_converter.go
  service/history/replication/executable_task_mock.go
  service/history/replication/executable_task_test.go
  service/history/replication/executable_unknown_task.go
  service/history/replication/executable_verify_versioned_transition_task.go
  service/history/replication/executable_verify_versioned_transition_task_test.go
  service/history/replication/executable_workflow_state_task.go
  service/history/replication/executable_workflow_state_task_test.go
  service/history/replication/raw_task_converter.go
  service/history/replication/raw_task_converter_mock.go
  service/history/replication/stream_sender.go
  service/history/replication/stream_sender_test.go
Labels: teams/cgs

#7881 check if callbacks exist when reapply events
  service/history/interfaces/mutable_state.go
  service/history/interfaces/mutable_state_mock.go
  service/history/ndc/workflow_resetter.go
  service/history/ndc/workflow_resetter_test.go
  service/history/workflow/mutable_state_impl.go
  service/history/workflow/mutable_state_impl_test.go
Labels: teams/cgs

#7922 Fix buffered events ordering
  common/persistence/sql/sqlplugin/mysql/execution.go
  common/persistence/sql/sqlplugin/postgresql/execution.go
  common/persistence/sql/sqlplugin/sqlite/execution.go
Labels: codex

#7928 Fix QPS calculation in force replication wf
  service/worker/migration/force_replication_workflow.go
  service/worker/migration/force_replication_workflow_test.go
Labels: teams/cgs

#7969 fix missing new run
  api/persistence/v1/executions.pb.go
  proto/internal/temporal/server/api/persistence/v1/executions.proto
  service/history/interfaces/mutable_state.go
  service/history/interfaces/mutable_state_mock.go
  service/history/replication/sync_state_retriever.go
  service/history/workflow/context.go
  service/history/workflow/mutable_state_impl.go
  tests/xdc/failover_test.go
Labels: teams/cgs
