Repository temporalio/temporal, pull requests merged in 2025-03, with the labels that each got.

#7423 Double QPS queue size for estimator
  service/worker/migration/force_replication_workflow.go
  service/worker/migration/force_replication_workflow_test.go
Labels: teams/cgs

#7438 Adding finer replication metrics
  .golangci.yml
  common/metrics/metric_defs.go
  common/metrics/tags.go
  service/history/ndc/activity_state_replicator.go
  service/history/ndc/activity_state_replicator_test.go
  service/history/replication/bi_direction_stream.go
  service/history/replication/executable_task.go
  service/history/replication/metrics.go
  service/history/replication/stream_receiver.go
  service/history/replication/stream_sender.go
  service/history/replication/stream_sender_test.go
Labels: teams/cgs

#7448 stop infinite activity retries in the entity workflows
  service/worker/workerdeployment/util.go
  service/worker/workerdeployment/version_workflow.go
Labels: release/1.27.2

#7414 [CHASM] Cassandra Persistence for CHASM nodes
  chasm/tree.go
  common/metrics/metric_defs.go
  common/persistence/cassandra/mutable_state_store.go
  common/persistence/cassandra/util.go
  common/persistence/data_interfaces.go
  common/persistence/execution_manager.go
  common/persistence/persistence_interface.go
  common/persistence/serialization/serializer.go
  common/persistence/size.go
  common/persistence/tests/execution_mutable_state.go
  common/persistence/tests/util.go
  schema/cassandra/temporal/schema.cql
  schema/cassandra/temporal/versioned/v1.12/chasm_node_map.cql
  schema/cassandra/temporal/versioned/v1.12/manifest.json
  schema/cassandra/version.go
  service/history/workflow/metrics.go
Labels: schema changes

#7452 Apply backoff retry for application error in replication stream
  service/history/replication/stream.go
  service/history/replication/stream_receiver.go
  service/history/replication/stream_sender.go
  service/history/replication/stream_test.go
Labels: teams/cgs

#7456 Update replication task page size
  common/dynamicconfig/constants.go
  common/metrics/metric_defs.go
  service/history/replication/ack_manager.go
Labels: teams/cgs

#7478 Return error for non retry case in stream sender
  service/history/replication/stream.go
Labels: teams/cgs

#7455 [CHASM] SQL persistence for CHASM nodes
  common/persistence/sql/execution.go
  common/persistence/sql/execution_state_map.go
  common/persistence/sql/execution_util.go
  common/persistence/sql/sqlplugin/history_chasm.go
  common/persistence/sql/sqlplugin/interfaces.go
  common/persistence/sql/sqlplugin/mysql/execution_maps.go
  common/persistence/sql/sqlplugin/postgresql/execution_maps.go
  common/persistence/sql/sqlplugin/sqlite/execution_maps.go
  common/persistence/sql/sqlplugin/tests/history_execution_chasm.go
  common/persistence/tests/mysql_test.go
  common/persistence/tests/postgresql_test.go
  common/persistence/tests/sqlite_test.go
  common/persistence/tests/util.go
  schema/mysql/v8/temporal/schema.sql
  schema/mysql/v8/temporal/versioned/v1.17/add_chasm_node_maps.sql
  schema/mysql/v8/temporal/versioned/v1.17/manifest.json
  schema/mysql/v8/version.go
  schema/postgresql/v12/temporal/schema.sql
  schema/postgresql/v12/temporal/versioned/v1.17/add_chasm_node_maps.sql
  schema/postgresql/v12/temporal/versioned/v1.17/manifest.json
  schema/postgresql/v12/version.go
  schema/sqlite/v3/temporal/schema.sql
  schema/sqlite/v3/temporal/versioned/v0.9/add_chasm_node_maps.sql
  schema/sqlite/v3/temporal/versioned/v0.9/manifest.json
  schema/sqlite/version.go
Labels: schema changes

#7505 Start stream sender before register
  service/history/handler.go
Labels: teams/cgs

#7510 Reduce max proto duration cap to 100 years
  common/primitives/timestamp/duration.go
Labels: release/1.27.2

#7479 Propagate stream server context to downstream
  service/history/replication/stream.go
  service/history/replication/stream_receiver.go
  service/history/replication/stream_sender.go
  service/history/replication/stream_sender_flow_controller.go
  service/history/replication/stream_sender_flow_controller_mock.go
  service/history/replication/stream_sender_flow_controller_test.go
  service/history/replication/stream_sender_test.go
  service/history/replication/stream_test.go
Labels: teams/cgs

#7535 Fix replication metrics
  common/metrics/metric_defs.go
  service/history/replication/executable_task.go
Labels: teams/cgs
