Repository temporalio/temporal, pull requests merged in 2025-02, with the labels that each got.

#7296 Workflow Update: abort updates with non-retryable error if WFT fails unexpectedly
  service/history/api/respondworkflowtaskcompleted/api.go
  service/history/workflow/update/abort_reason.go
  service/history/workflow/update/errors_failures.go
  service/history/workflow/update/update.go
  tests/update_workflow_test.go
Labels: release/1.27.0

#7303 Revert "Always use OTEL as metric handler (#7265)"
  common/metrics/config.go
  common/metrics/config_test.go
Labels: release/1.27.0

#7328 Update dependencies
  go.mod
  go.sum
Labels: release/1.27.0

#7337 Add back 250 year max duration cap
  common/primitives/timestamp/duration.go
  common/primitives/timestamp/duration_test.go
  common/retrypolicy/retry_policy.go
  components/nexusoperations/workflow/commands.go
  service/frontend/namespace_handler.go
  service/frontend/workflow_handler.go
  service/history/api/command_attr_validator.go
  service/history/api/create_workflow_util.go
  service/worker/scheduler/spec.go
Labels: release/1.27.0

#7333 Use modernc.org/sqlite version v1.34.1
  Makefile
  go.mod
  go.sum
Labels: release/1.27.0

#7346 [Reset] Set AllowResetWithPendingChildren to true by default
  common/dynamicconfig/constants.go
Labels: release/1.27.0

#7366 Remove all sources of worker deployment NDE detectable by static workflowcheck
  service/worker/workerdeployment/drainage_workflow.go
  service/worker/workerdeployment/replay_test.go
  service/worker/workerdeployment/testdata/replay_deployment-workflow_initial.json.gz
  service/worker/workerdeployment/testdata/replay_deployment-workflow_maprange.json.gz
  service/worker/workerdeployment/testdata/replay_drainage-workflow_initial.json.gz
  service/worker/workerdeployment/testdata/replay_drainage-workflow_timenow.json.gz
  service/worker/workerdeployment/testdata/replay_version-workflow_initial.json.gz
  service/worker/workerdeployment/testdata/replay_version-workflow_maprange.json.gz
  service/worker/workerdeployment/version_workflow.go
  service/worker/workerdeployment/workflow.go
Labels: release/1.27.0

#7339 De-dup concurrent requests in ramping, current and delete updates
  service/worker/workerdeployment/client.go
  service/worker/workerdeployment/workflow.go
  tests/worker_deployment_test.go
  tests/worker_deployment_version_test.go
Labels: release/1.27.0

#7343 set status to DRAINING immediately after stop accepting new workflows
  service/worker/workerdeployment/drainage_workflow.go
  service/worker/workerdeployment/version_workflow.go
  service/worker/workerdeployment/workflow.go
Labels: release/1.27.0

#7368 make sure child completion reports to correct branch
  api/historyservice/v1/request_response.pb.go
  proto/internal/temporal/server/api/historyservice/v1/request_response.proto
  service/history/api/recordchildworkflowcompleted/api.go
  service/history/history_engine2_test.go
  service/history/transfer_queue_active_task_executor.go
  service/history/transfer_queue_active_task_executor_test.go
Labels: teams/cgs

#7385 Delete Namespace: fix incompatible change in reclaim resources workflow
  service/worker/deletenamespace/reclaimresources/workflow.go
Labels: release/1.27.1

#7388 Attempt to fix random describe errors
  service/worker/workerdeployment/client.go
Labels: release/1.27.1

#7389 Fix start time calculation in schedule spec
  components/scheduler/spec_processor.go
  service/worker/scheduler/spec.go
  service/worker/scheduler/spec_test.go
  service/worker/scheduler/workflow.go
Labels: release/1.27.1

#7394 Remove schedule spec version
  components/scheduler/spec_processor.go
  service/worker/scheduler/spec.go
  service/worker/scheduler/spec_test.go
  service/worker/scheduler/workflow.go
Labels: release/1.27.1

#7399 Non-Retryable error returned when deleting current/ramping version
  service/worker/workerdeployment/client.go
  tests/worker_deployment_version_test.go
Labels: release/1.27.2

#7398 Sorting version summaries in DescribeWorkerDeployment calls
  service/worker/workerdeployment/client.go
  tests/worker_deployment_test.go
Labels: release/1.27.2
